### ISSUE TITLE
Add method to set User-Agent, Chromium Debug Port, and Product Version

### ISSUE THREAD

**Issue by JoshEngebretson** [uWebKit/uWebKit#12]
This is mostly working, should be in by tomorrow

**Comment by ovjang** [comment]
I'm counting on you.

**Comment by JoshEngebretson** [comment]
This is all in the latest beta: http://www.uwebkit.com/static/downloads/uwebkit/uWebKit3_Beta1_p4.zip

Please see UWKConfig.cs for settings
