### ISSUE TITLE
Plugin crashes (don't work) on Windows (8.1) Standalone build - even simplest example!

### ISSUE THREAD

**Issue by kkostecki** [uWebKit/uWebKit#130]
We could not run any web view on Windows standalone build.

I have checked the simplest example scene (Example3WebTexture.scene) added in the plugin bundle and it also crashes when run as standalone application!!!

I have even changed the website to be displayed for the simplest one:
http://www.w3schools.com/html/tryhtml_basic_document.htm

and still could not get it working!!!

Please verify and fix the issue !!! We have bought 2 licenses for 95$ and we got nothing but plugin working with editor only!

Here is the output:
----------------------------------------------------------------------------------------------------------

Initialize engine version: 5.0.0f4 (5b98b70ebeb9)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 10.0]
    Renderer: NVIDIA GeForce 9800 GTX/9800 GTX+ (ID=0x612)
    Vendor:   NVIDIA
    VRAM:     480 MB
Begin MonoManager ReloadAssembly
Platform assembly: D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\UnityEngine.dll (this message is harmless)
Loading D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
- Completed reload, in  0.080 seconds
desktop: 1680x1050 59Hz; virtual: 1680x1050 at 0,0
<RI> Initializing input.

XInput1_3.dll not found.
<RI> Input initialized.

<RI> Initialized touch support.

Platform assembly: D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Managed\System.Core.dll (this message is harmless)
Crash!!!
SymInit: Symbol-SearchPath: '.;D:\FunUniverse\lpy;D:\FunUniverse\build_lpy;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'kkostecki'
OS-Version: 6.2.9200 () 0x300-0x1
D:\FunUniverse\build_lpy\WebViewWebTextureExample.exe:WebViewWebTextureExample.exe (01270000), size: 16420864 (result: 0), SymType: '-exported-', PDB: 'D:\FunUniverse\build_lpy\WebViewWebTextureExample.exe', fileVersion: 5.0.0.39095
C:\Windows\SYSTEM32\ntdll.dll:ntdll.dll (77B60000), size: 1499136 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ntdll.dll', fileVersion: 6.3.9600.17668
C:\Windows\SYSTEM32\KERNEL32.DLL:KERNEL32.DLL (75580000), size: 1310720 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\KERNEL32.DLL', fileVersion: 6.3.9600.17056
C:\Windows\SYSTEM32\KERNELBASE.dll:KERNELBASE.dll (760D0000), size: 851968 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\KERNELBASE.dll', fileVersion: 6.3.9600.17278
C:\Windows\system32\apphelp.dll:apphelp.dll (684C0000), size: 626688 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\apphelp.dll', fileVersion: 6.3.9600.17031
C:\Windows\SYSTEM32\HID.DLL:HID.DLL (748D0000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\HID.DLL', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\WS2_32.dll:WS2_32.dll (77A40000), size: 315392 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\WS2_32.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\USER32.dll:USER32.dll (77650000), size: 1359872 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\USER32.dll', fileVersion: 6.3.9600.17344
C:\Windows\SYSTEM32\VERSION.dll:VERSION.dll (753D0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\VERSION.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\ole32.dll:ole32.dll (77500000), size: 1097728 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ole32.dll', fileVersion: 6.3.9600.17042
C:\Windows\SYSTEM32\SHLWAPI.dll:SHLWAPI.dll (76200000), size: 266240 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\SHLWAPI.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\ADVAPI32.dll:ADVAPI32.dll (756E0000), size: 491520 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ADVAPI32.dll', fileVersion: 6.3.9600.17031
C:\Windows\SYSTEM32\GDI32.dll:GDI32.dll (75470000), size: 1077248 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\GDI32.dll', fileVersion: 6.3.9600.17246
C:\Windows\SYSTEM32\SHELL32.dll:SHELL32.dll (76250000), size: 19578880 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\SHELL32.dll', fileVersion: 6.3.9600.17680
C:\Windows\SYSTEM32\OPENGL32.dll:OPENGL32.dll (5FD50000), size: 868352 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\OPENGL32.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\WINMM.dll:WINMM.dll (74850000), size: 131072 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\WINMM.dll', fileVersion: 6.3.9600.17078
C:\Windows\SYSTEM32\OLEAUT32.dll:OLEAUT32.dll (77830000), size: 610304 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\OLEAUT32.dll', fileVersion: 6.3.9600.17560
C:\Windows\SYSTEM32\MSACM32.dll:MSACM32.dll (6D070000), size: 86016 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\MSACM32.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\IMM32.dll:IMM32.dll (75C10000), size: 151552 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\IMM32.dll', fileVersion: 6.3.9600.17031
C:\Windows\SYSTEM32\DNSAPI.dll:DNSAPI.dll (74CB0000), size: 507904 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\DNSAPI.dll', fileVersion: 6.3.9600.17039
C:\Windows\SYSTEM32\IPHLPAPI.DLL:IPHLPAPI.DLL (74D40000), size: 122880 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\IPHLPAPI.DLL', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\WINHTTP.dll:WINHTTP.dll (751B0000), size: 606208 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\WINHTTP.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\msvcrt.dll:msvcrt.dll (757A0000), size: 778240 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\msvcrt.dll', fileVersion: 7.0.9600.16384
C:\Windows\SYSTEM32\NSI.dll:NSI.dll (75DE0000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\NSI.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\RPCRT4.dll:RPCRT4.dll (75DF0000), size: 720896 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\RPCRT4.dll', fileVersion: 6.3.9600.17216
C:\Windows\SYSTEM32\combase.dll:combase.dll (75F80000), size: 1368064 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\combase.dll', fileVersion: 6.3.9600.17031
C:\Windows\SYSTEM32\sechost.dll:sechost.dll (75EA0000), size: 253952 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\sechost.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\GLU32.dll:GLU32.dll (5FD20000), size: 147456 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\GLU32.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\DDRAW.dll:DDRAW.dll (5FC30000), size: 946176 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\DDRAW.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\WINMMBASE.dll:WINMMBASE.dll (74310000), size: 131072 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\WINMMBASE.dll', fileVersion: 6.3.9600.17080
C:\Windows\SYSTEM32\MSCTF.dll:MSCTF.dll (75AF0000), size: 1122304 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\MSCTF.dll', fileVersion: 6.3.9600.17664
C:\Windows\SYSTEM32\WINNSI.DLL:WINNSI.DLL (74D30000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\WINNSI.DLL', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\SspiCli.dll:SspiCli.dll (75450000), size: 118784 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\SspiCli.dll', fileVersion: 6.3.9600.16408
C:\Windows\SYSTEM32\DCIMAN32.dll:DCIMAN32.dll (5FC20000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\DCIMAN32.dll', fileVersion: 6.3.9600.17415
C:\Windows\SYSTEM32\cfgmgr32.dll:cfgmgr32.dll (77610000), size: 237568 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\cfgmgr32.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\DEVOBJ.dll:DEVOBJ.dll (75350000), size: 126976 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\DEVOBJ.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\CRYPTBASE.dll:CRYPTBASE.dll (75440000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\CRYPTBASE.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\bcryptPrimitives.dll:bcryptPrimitives.dll (753E0000), size: 335872 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\bcryptPrimitives.dll', fileVersion: 6.3.9600.17120
C:\Windows\SYSTEM32\shcore.dll:shcore.dll (74C10000), size: 569344 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\shcore.dll', fileVersion: 6.3.9600.17666
D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Mono\mono.dll:mono.dll (10000000), size: 2289664 (result: 0), SymType: '-exported-', PDB: 'D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Mono\mono.dll'
C:\Windows\SYSTEM32\PSAPI.DLL:PSAPI.DLL (756D0000), size: 24576 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\PSAPI.DLL', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\MSWSOCK.dll:MSWSOCK.dll (74D60000), size: 282624 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\MSWSOCK.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\kernel.appcore.dll:kernel.appcore.dll (74A80000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\kernel.appcore.dll', fileVersion: 6.3.9600.16384
C:\Windows\system32\uxtheme.dll:uxtheme.dll (749A0000), size: 897024 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\uxtheme.dll', fileVersion: 6.3.9600.17031
C:\Windows\system32\dwmapi.dll:dwmapi.dll (74370000), size: 98304 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\system32\dwmapi.dll', fileVersion: 6.3.9600.17238
C:\Windows\SYSTEM32\d3d11.dll:d3d11.dll (6E250000), size: 1765376 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\d3d11.dll', fileVersion: 6.3.9600.17041
C:\Windows\SYSTEM32\dxgi.dll:dxgi.dll (6E400000), size: 401408 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\dxgi.dll', fileVersion: 6.3.9600.17201
C:\Windows\SYSTEM32\nvwgf2um.dll:nvwgf2um.dll (6D2F0000), size: 16080896 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\nvwgf2um.dll', fileVersion: 9.18.13.4052
C:\Windows\SYSTEM32\bcrypt.dll:bcrypt.dll (74B30000), size: 118784 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\bcrypt.dll', fileVersion: 6.3.9600.17031
C:\Windows\SYSTEM32\MMDevAPI.DLL:MMDevAPI.DLL (73E90000), size: 303104 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\MMDevAPI.DLL', fileVersion: 6.3.9600.17031
C:\Windows\SYSTEM32\wdmaud.drv:wdmaud.drv (5FBE0000), size: 212992 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\wdmaud.drv', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\ksuser.dll:ksuser.dll (67AC0000), size: 28672 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\ksuser.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\AVRT.dll:AVRT.dll (6CF00000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\AVRT.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (73F40000), size: 393216 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\AUDIOSES.DLL', fileVersion: 6.3.9600.17415
C:\Windows\SYSTEM32\powrprof.dll:powrprof.dll (73EE0000), size: 253952 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\powrprof.dll', fileVersion: 6.3.9600.17031
C:\Windows\SYSTEM32\msacm32.drv:msacm32.drv (5FBD0000), size: 36864 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\msacm32.drv', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\midimap.dll:midimap.dll (5FBC0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\midimap.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\dsound.dll:dsound.dll (5FFD0000), size: 495616 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\dsound.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\clbcatq.dll:clbcatq.dll (75860000), size: 512000 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\clbcatq.dll', fileVersion: 2001.12.10530.16384
C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.17031_none_a9efdb8b01377ea7\comctl32.dll:comctl32.dll (74120000), size: 1990656 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.17031_none_a9efdb8b01377ea7\comctl32.dll', fileVersion: 6.10.9600.17031
D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Plugins\UWKPlugin.dll:UWKPlugin.dll (5FAE0000), size: 892928 (result: 0), SymType: '-exported-', PDB: 'D:\FunUniverse\build_lpy\WebViewWebTextureExample_Data\Plugins\UWKPlugin.dll'
C:\Windows\SYSTEM32\profapi.dll:profapi.dll (74400000), size: 57344 (result: 0), SymType: '-nosymbols-', PDB: 'C:\Windows\SYSTEM32\profapi.dll', fileVersion: 6.3.9600.16384
C:\Windows\SYSTEM32\dbghelp.dll:dbghelp.dll (6CF20000), size: 1343488 (result: 0), SymType: '-exported-', PDB: 'C:\Windows\SYSTEM32\dbghelp.dll', fileVersion: 6.3.9600.16520

========== OUTPUTING STACK TRACE ==================

760E2F71 (KERNELBASE) RaiseException
5FB73EEE (UWKPlugin) UnityRenderEvent
5FAFD75B (UWKPlugin) UnityRenderEvent

When I build the app for x86_64 I have a little bit more in stack trace:

========== OUTPUTING STACK TRACE ==================

00007FFA06B5606C (KERNELBASE) RaiseException
00007FF9FA40FA25 (UWKPlugin) UnityRenderEvent
00007FF9FA3834DD (UWKPlugin) UnityRenderEvent
00007FF9FA383DEE (UWKPlugin) UnityRenderEvent
00007FF9FA38211D (UWKPlugin) UnityRenderEvent
00007FF9FA366924 (UWKPlugin) UnityRenderEvent
00007FF9FA3633B3 (UWKPlugin) UWK_DevelopmentOnlyHangWebProcess
00007FF9FA363420 (UWKPlugin) UWK_Initialize
000000000336E635 (Mono JIT Code) (wrapper managed-to-native) UWKPlugin:UWK_Initialize (LogCallbackDelegate,LogErrorDelegate,ProcessMessageDelegate,intptr)
000000000335F6EB (Mono JIT Code) UWKPlugin:Initialize ()
000000000335E92C (Mono JIT Code) UWKCore:Init ()
000000000335D908 (Mono JIT Code) UWKWebView:Awake ()
000000000335725B (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
00007FF9F5263DF7 (mono) mono_set_defaults
00007FF9F51B82A1 (mono) mono_runtime_invoke
00007FF6A5CD5725 (WebViewWebTextureExample_x64) ScriptingArguments::AddString
00007FF6A5CD57D1 (WebViewWebTextureExample_x64) ScriptingArguments::AddString
00007FF6A5BFB835 (WebViewWebTextureExample_x64) ReportScriptingObjectsTransfer::operator=
00007FF6A5BFEA41 (WebViewWebTextureExample_x64) GetMonoBehaviourInConstructor
00007FF6A5BFBFC8 (WebViewWebTextureExample_x64) ReportScriptingObjectsTransfer::operator=
00007FF6A5CF2924 (WebViewWebTextureExample_x64) RegisterAllowNameConversionInDerivedTypes
00007FF6A5CF2C5A (WebViewWebTextureExample_x64) RegisterAllowNameConversionInDerivedTypes
00007FF6A5CA5E99 (WebViewWebTextureExample_x64) CallbackArray3<std::basic_string<char,std::char_traits<char>,stl_allocator<char,58,16> > const & __ptr64,AwakeFromLoadQueue & __ptr64,enum LoadLevelOperation::LoadingMode>::Invoke
00007FF6A5C939BB (WebViewWebTextureExample_x64) UserList::AddUser
00007FF6A5C92EF5 (WebViewWebTextureExample_x64) UserList::AddUser
00007FF6A5C92FAE (WebViewWebTextureExample_x64) UserList::AddUser
00007FF6A5C8F840 (WebViewWebTextureExample_x64) UserList::AddUser
00007FF6A5D4E941 (WebViewWebTextureExample_x64) PlayerMainWndProc
00007FF6A5D5107C (WebViewWebTextureExample_x64) PlayerWinMain
00007FF6A61218E8 (WebViewWebTextureExample_x64) RectT<int>::GetBottom
00007FFA073C16AD (KERNEL32) BaseThreadInitThunk
00007FFA0957E954 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

**** Crash! ****

**Comment by JoshEngebretson** [comment]
Hello, Unity 5 final introduced a path issue.  The latest version should fix this: http://www.uwebkit.com/static/downloads/uwebkit/uWebKit2_20p6.unitypackage

If you would rather update the script in your project, you can see the change here: https://github.com/uWebKit/uWebKit/commit/384f590e1ec276f8cecdaf67bc56c854b99a016d

**Comment by kkostecki** [comment]
Works like a charm :+1: , I was so desperate that I have almost dig into .dll's :). But stacked on the Poco exception, so I supposed that the problem lays in the Poco code you have used.

Anyway BIG THANX for a fast answer.
