### ISSUE TITLE
Oculus mouse issue

### ISSUE THREAD

**Issue by zealousappex** [uWebKit/uWebKit#132]
Mouse inputs are not working when including the Oculus OVR.
Does any one know how to work around this?

**Comment by grobm** [comment]
It's a bigger issue. You need to look at Implementing a VRGUI namespace. The old GUI methods are not supported when it comes to Oculus. It's the Stereocamera that are causing your issue. The current implementation here assumes a single camera for implementation of the ray for the cursor.

Ping me, if you need help.

**Comment by grobm** [comment]
Side note, I wished Untiy Tech, would add a specific Input method for VR and VR stereo implementation.

**Comment by zealousappex** [comment]
Thank you so much for your help grom!

I've included VRGUI in the project and attached it to the OVRCameraRig.
I'm seeing the cursor.
Sometime I'm able to click on a link but the click position seems to be way off from the cursors position.
If I am able to click I can only do it once to navigate in uWebKit.

Is my issue that I can't use a 3d gameobject, or I don't have my VRGUI attached in the right place?
I've included a screen shot, 
I am getting a javascript error about "device=width;" for key "width" is invalid, and has been ignored.
![capture](https://cloud.githubusercontent.com/assets/12189170/7419771/f400c420-ef3c-11e4-95e8-2d8058dbc5f2.JPG)

**Comment by grobm** [comment]
It sound like were you are positioning the scripts, maybe or how your encapsulation your code.

I will post something for you to compare. 

Your issue is about Oculus, not uWebkit.

-Mark Grob
845.978.9054

**Comment by zealousappex** [comment]
Thank you!

**Comment by grobm** [comment]
Here is a rush job on a sample that works on my system.

using UnityEngine;
using System.Collections;

public class ExampleMenu : VRGUI 
{
	public GUISkin skin;
	
	private int clickCount = 0;
	public Vector2 Position;
	
	// Whether the GUI accepts mouse/keyboard input
	public bool HasFocus = true;
	
	public override void OnVRGUI()
	{
		GUI.skin = skin;
		
		GUILayout.BeginArea(new Rect(0f, 0f, Screen.width, Screen.height));

		// get the attached view component
		UWKWebView view = gameObject.GetComponent<UWKWebView>();
		
		// if we have a view attached and it is visible
		if (view != null && view.Visible())
		{
			
			// draw it
			Rect r = new Rect (Position.x, Position.y, view.CurrentWidth, view.CurrentHeight);
			view.DrawTexture (r);
			
			// if we have focus, handle input
			if (HasFocus)
			{
				// get the mouse coordinate
				Vector3 mousePos = Input.mousePosition;
				mousePos.y = Screen.height - mousePos.y; 
				
				// translate based on position
				mousePos.x -= Position.x;
				mousePos.y -= Position.y;    
				
				view.ProcessMouse(mousePos);            
				
				// process keyboard     
				if (Event.current.isKey)
					view.ProcessKeyboard(Event.current);
			}
		}       

		GUILayout.BeginVertical();
		GUILayout.FlexibleSpace();
		
		GUILayout.BeginHorizontal();
		GUILayout.FlexibleSpace();
//		if (GUILayout.Button("Click Me!"))
//		{
//			clickCount++;
//		}
		GUILayout.FlexibleSpace();
		GUILayout.EndHorizontal();
		
		GUILayout.BeginHorizontal();
//		GUILayout.FlexibleSpace();
//		GUILayout.Label("Clicks: " + clickCount);
//		GUILayout.FlexibleSpace();
		GUILayout.EndHorizontal();
		
		GUILayout.FlexibleSpace();
		GUILayout.EndVertical();
		GUILayout.EndArea();
	}
}

**Comment by grobm** [comment]
Note the switch from MonoBehavior -> VRGUI in the Class.

And the 

public override void OnVRGUI() <=== here is were I think you forgot to do.

**Comment by grobm** [comment]
Send me your script offline if they still have issues. grobm10 <at> gmail <dot> com.

**Comment by grobm** [comment]
Side note, one thing I am trying to figure out is how to enable ad disable the mouse + inputs when I am not looking at it.

Working on a VR workspace app... if you have ideas.

**Comment by zealousappex** [comment]
That code works great!
I added to your code the ability to stop the input when not looking at the object.
I actually thought, hey if they aren't looking at it why even render it, so I put the boolean for the draw statement.

   private Transform target;

    void Start()
    {
        target = this.transform;
    }

    void Update()
    {
        Vector3 viewPos = Camera.main.WorldToViewportPoint(target.position);
        if ((0f <= viewPos.x && viewPos.x <= 1F) && (0f <= viewPos.y && viewPos.y <= 1F) && (Camera.main.transform.position.z < this.transform.position.z))
        {
            print("target is in the camera! ----- ");
            IsVisible = true;
        }
        else if ((0f > viewPos.x))
        {
            print("target is on the left side!");
            IsVisible = true;
        }
        else if ((viewPos.x > 1F))
        {
            print("target is on the right side!");
            IsVisible = true;
        }
        else
        {
            print("target is NOT in the camera!");
            IsVisible = false;
        }
    }

**Comment by zealousappex** [comment]
Here is your code with the little bit I added:
using UnityEngine;
using System.Collections;

public class CameraGUI : VRGUI
{

    public GUISkin skin;

    private int clickCount = 0;
    public Vector2 Position;

    // Whether the GUI accepts mouse/keyboard input
    public bool HasFocus = true;
    public bool IsVisible = true;

    private Transform target;

    void Start()
    {
        target = this.transform;
    }

    void Update()
    {
        Vector3 viewPos = Camera.main.WorldToViewportPoint(target.position);
        if ((0f <= viewPos.x && viewPos.x <= 1F) && (0f <= viewPos.y && viewPos.y <= 1F) && (Camera.main.transform.position.z < this.transform.position.z))
        {
            print("target is in the camera! ----- ");
            IsVisible = true;
        }
        else if ((0f > viewPos.x))
        {
            print("target is on the left side!");
            IsVisible = true;
        }
        else if ((viewPos.x > 1F))
        {
            print("target is on the right side!");
            IsVisible = true;
        }
        else
        {
            print("target is NOT in the camera!");
            IsVisible = false;
        }
    }

    public override void OnVRGUI()
    {
        GUI.skin = skin;

        GUILayout.BeginArea(new Rect(0f, 0f, Screen.width, Screen.height));

        // get the attached view component
        UWKWebView view = gameObject.GetComponent<UWKWebView>();

        // if we have a view attached and it is visible
        if (view != null && view.Visible() && IsVisible)
        {

            // draw it
            Rect r = new Rect(Position.x, Position.y, view.CurrentWidth, view.CurrentHeight);
            view.DrawTexture(r);

            // if we have focus, handle input
            if (HasFocus)
            {
                // get the mouse coordinate
                Vector3 mousePos = Input.mousePosition;
                mousePos.y = Screen.height - mousePos.y;

                // translate based on position
                mousePos.x -= Position.x;
                mousePos.y -= Position.y;

                view.ProcessMouse(mousePos);

                // process keyboard     
                if (Event.current.isKey)
                    view.ProcessKeyboard(Event.current);
            }
        }

        GUILayout.BeginVertical();
        GUILayout.FlexibleSpace();

        GUILayout.BeginHorizontal();
        GUILayout.FlexibleSpace();
        // if (GUILayout.Button("Click Me!"))
        // {
        // clickCount++;
        // }
        GUILayout.FlexibleSpace();
        GUILayout.EndHorizontal();

        GUILayout.BeginHorizontal();
        GUILayout.FlexibleSpace();
        GUILayout.Label("Clicks: " + clickCount);
        GUILayout.FlexibleSpace();
        GUILayout.EndHorizontal();

        GUILayout.FlexibleSpace();
        GUILayout.EndVertical();
        GUILayout.EndArea();
    }
}

**Comment by zealousappex** [comment]
BTW my issue before was I had placed the uWebKit on a Plane and rotated it, which made the Rect come in at the wrong rotation.
I create a empty object and everything worked!
Thanks again!
