### ISSUE TITLE
Change the "ZTest always" shader? 

### ISSUE THREAD

**Issue by grobm** [uWebKit/uWebKit#138]
Is it possible to change the screens are drawn with a “ZTest always” shader (i.e. they always appear, regardless of depth or occlusion).

I am getting a shader conflict with some other code and it is "blinking" or "blind" effect with my shader? 
![image001](https://cloud.githubusercontent.com/assets/10155745/7951806/ff7f4720-0979-11e5-80e4-1e8d7822fcff.png)

Video here:
https://youtu.be/rf_gvRjNIqA

**Comment by JoshEngebretson** [comment]
Hello,

This looks like a really interesting use case.  I am confused though as far as rendering, uWebKit is ultimately just a Texture2D.

- Josh

**Comment by grobm** [comment]
I am rendering the Texture2D into a quad in a 3D space. What I am seeing is a Ztest rendering affect in this environment. It might be an issue with Unity's Engine.

**Comment by grobm** [comment]
Here is the Shader for rendering the content:

Shader "VRGUITransparentOverlayShader" 
{
	Properties 
	{
		_MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
	}

SubShader 
{
	Tags {"Queue"="Overlay" "IgnoreProjector"="True" "RenderType"="Overlay"}
	LOD 100
	
	ZWrite Off
	ZTest Always
	Blend SrcAlpha OneMinusSrcAlpha 
	
		Pass {  
			CGPROGRAM
				#pragma vertex vert
				#pragma fragment frag
				
				#include "UnityCG.cginc"
	
				struct appdata_t 
				{
					float4 vertex : POSITION;
					float2 texcoord : TEXCOORD0;
				};
	
				struct v2f 
				{
					float4 vertex : SV_POSITION;
					half2 texcoord : TEXCOORD0;
				};
	
				sampler2D _MainTex;
				float4 _MainTex_ST;
				
				v2f vert (appdata_t v)
				{
					v2f o;
					o.vertex = mul(UNITY_MATRIX_MVP, v.vertex);
					o.texcoord = TRANSFORM_TEX(v.texcoord, _MainTex);
					return o;
				}
				
				fixed4 frag (v2f i) : COLOR
				{
					fixed4 col = tex2D(_MainTex, i.texcoord);
					return col;
				}
			ENDCG
		}
	}

	SubShader 
	{
		Tags {"Queue"="Overlay" "IgnoreProjector"="True" "RenderType"="Overlay"}
		LOD 100
		
		ZWrite Off
		ZTest Always
		Blend SrcAlpha OneMinusSrcAlpha 
	
		Pass 
		{
			Lighting Off
			SetTexture [_MainTex] { combine texture } 
		}
	}
}

**Comment by grobm** [comment]
Changed the Subshader to make "ZTest Always" to  "ZTest Less", this appeared to fix the issue.
