### ISSUE TITLE
OpenGL renderer not working with Windows

### ISSUE THREAD

**Issue by romlel** [uWebKit/uWebKit#142]
Hello all

For our use of uWebkit, we require forced OpenGL in Windows mode because of other plugins we use, and uWebKit seems to only allow OpenGL when we use a Mac. 
uWebKit  with Windows works only in DX9/11 mode.

As the website FAQ indicates "High performance Direct3D9/11 and OpenGL renderers", would it be possible to make the adaptations and fix this ?

On the forum thread (#241), someone of uWebKit staff indicated that the keypoint was about "OSX IOSurfaces" and that "it would be possible to adapt the OpenGL renderer to also work under Windows"

Thanks a lot and best regards.

**Comment by JoshEngebretson** [comment]
Hello,

uWebKit2 supports D3D9/11 on Windows and OpenGL on OSX.  We do not have plans to support OpenGL mode on windows.  

I filed an issue to make this clear on the site and faq: https://github.com/uWebKit/uWebKit/issues/143

**Comment by romlel** [comment]
Understood, thanks for your answer

Then, could you also change on the following page : "
https://github.com/uWebKit/uWebKit" the following line, disambiguating the
fact that OpenGL could be compatible with Windows :
"High performance Direct3D9/11 and OpenGL renderer"

Also, can I get a refund for uWebKit ? Finally, I cannot use it because of
this limitation

Best regards


2015-06-30 17:08 GMT+02:00 JoshEngebretson <notifications@github.com>:

> Hello,
>
> uWebKit2 supports D3D9/11 on Windows and OpenGL on OSX. We do not have
> plans to support OpenGL mode on windows.
>
> I filed an issue to make this clear on the site and faq: #143
> <https://github.com/uWebKit/uWebKit/issues/143>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uWebKit/uWebKit/issues/142#issuecomment-117221035>.
>



-- 
Romain Lelong
06 99 52 05 30

**Comment by JoshEngebretson** [comment]
Hello,

uWebKit2 has a trial package to evaluate it's suitability for specific purposes.  If the purchase has been made within the last 30 days, we can offer a refund.  Please email sales@uwebkit.com with your receipt and date of purchase.

Thanks
