### ISSUE TITLE
UWKPlugin crashes on Windows 8.1 Intel HD 4000

### ISSUE THREAD

**Issue by st0nerhat** [uWebKit/uWebKit#145]
When I try to load a url with UWKPlugin on Windows, I get the following crash:

 	ntdll.dll!RtlEnterCriticalSection()	Unknown
>	mono.dll!mono_jit_info_table_find(_MonoDomain * domain, char * addr) Line 392	C
 	CKEDU.exe!StackWalker::ShowCallstack(void *,struct _CONTEXT const *,int (*)(void *,unsigned __int64,void *,unsigned long,unsigned long *,void *),void *,int)	Unknown
 	CKEDU.exe!winutils::ProcessInternalCrash(struct _EXCEPTION_POINTERS *,bool)	Unknown
 	KernelBase.dll!00007ff803651c72()	Unknown
 	ntdll.dll!RtlUserThreadStart$filt$0()	Unknown
 	ntdll.dll!__C_specific_handler()	Unknown
 	ntdll.dll!RtlpExecuteHandlerForException()	Unknown
 	ntdll.dll!RtlDispatchException()	Unknown
 	ntdll.dll!KiUserExceptionDispatch()	Unknown
 	nvwgf2umx.dll!00007fffd7de4f76()	Unknown
 	nvwgf2umx.dll!00007fffd7df3600()	Unknown
 	nvumdshimx.dll!00007fffffce1208()	Unknown
 	nvumdshimx.dll!00007fffffcde25d()	Unknown
 	nvumdshimx.dll!00007fffffcedf71()	Unknown
 	nvumdshimx.dll!00007fffffcd541d()	Unknown
 	d3d11.dll!00007ff80133c8f0()	Unknown
 	d3d11.dll!00007ff801346d78()	Unknown
 	UWKPlugin.dll!00007fffed2ff933()	Unknown
 	UWKPlugin.dll!00007fffed2fff4b()	Unknown
 	UWKPlugin.dll!00007fffed2e6345()	Unknown
 	CKEDU.exe!PluginsRenderMarker(int)	Unknown
 	CKEDU.exe!GfxDeviceWorker::RunCommand(class ThreadedStreamBuffer &)	Unknown
 	CKEDU.exe!GfxDeviceWorker::Run(void)	Unknown
 	CKEDU.exe!GfxDeviceWorker::RunGfxDeviceWorker(void *)	Unknown
 	CKEDU.exe!Thread::RunThreadWrapper(void *)	Unknown
 	kernel32.dll!00007ff8057713d2()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

**Comment by st0nerhat** [comment]
Build Target: Windows x86 and Windows x64
OS: Windows 8.1
Unity version: 5.0.4f1
Video card: Intel HD 4000 w/ NVIDIA GT 640M

**Comment by JoshEngebretson** [comment]
Please ensure that the Intel HD and NVIDIA drivers are up to date

**Comment by st0nerhat** [comment]
Will do.

**Comment by st0nerhat** [comment]
I updated the drivers to latest and am still experiencing the behavior.

Here is a portion of the DxDiag report:

------------------
System Information
------------------
Time of this report: 7/14/2015, 20:19:11
       Machine name: JENNAVAIO
   Operating System: Windows 8.1 64-bit (6.3, Build 9600) (9600.winblue_r9.150322-1500)
           Language: English (Regional Setting: English)
System Manufacturer: Sony Corporation
       System Model: SVS151290X
               BIOS: R0081C8
          Processor: Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz (8 CPUs), ~2.2GHz
             Memory: 12288MB RAM
Available OS Memory: 12168MB RAM
          Page File: 2402MB used, 11620MB available
        Windows Dir: C:\WINDOWS
    DirectX Version: DirectX 11
DX Setup Parameters: Not found
   User DPI Setting: 96 DPI (100 percent)
 System DPI Setting: 120 DPI (125 percent)
    DWM DPI Scaling: Disabled
     DxDiag Version: 6.03.9600.17415 64bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)

---------------
Display Devices
---------------
          Card name: Intel(R) HD Graphics 4000
       Manufacturer: Intel Corporation
          Chip type: Intel(R) HD Graphics Family
           DAC type: Internal
        Device Type: Full Device
         Device Key: Enum\PCI\VEN_8086&DEV_0166&SUBSYS_909C104D&REV_09
     Display Memory: 1792 MB
   Dedicated Memory: 32 MB
      Shared Memory: 1760 MB
       Current Mode: 1920 x 1080 (32 bit) (60Hz)
       Monitor Name: Digital Flat Panel (1920x1080 60Hz)
      Monitor Model: VAIO_LCD
         Monitor Id: MS_0025
        Native Mode: 1920 x 1080(p) (59.959Hz)
        Output Type: Internal
        Driver Name: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igdumdim32,igd10iumd32,igd10iumd32
Driver File Version: 10.18.0010.3496 (English)
     Driver Version: 10.18.10.3496
        DDI Version: 11
     Feature Levels: 11.0,10.1,10.0,9.3,9.2,9.1
       Driver Model: WDDM 1.3
Graphics Preemption: DMA
 Compute Preemption: Thread group
           Miracast: Supported
Hybrid Graphics GPU: Integrated
     Power P-states: Not Supported
  Driver Attributes: Final Retail
   Driver Date/Size: 10/7/2014 01:30:26, 26168168 bytes
        WHQL Logo'd: n/a
    WHQL Date Stamp: n/a
  Device Identifier: {D7B78E66-4226-11CF-3779-91B0B4C2C435}
          Vendor ID: 0x8086
          Device ID: 0x0166
          SubSys ID: 0x909C104D
        Revision ID: 0x0009
 Driver Strong Name: oem4.inf:5f63e5341859ec8c:iIVBM_w81:10.18.10.3496:pci\ven_8086&dev_0166&subsys_909c104d
     Rank Of Driver: 00DA0001
        Video Accel: ModeMPEG2_A ModeMPEG2_C ModeWMV9_C ModeVC1_C 
        DXVA2 Modes: DXVA2_ModeMPEG2_VLD  DXVA2_ModeMPEG2_IDCT  DXVA2_ModeWMV9_IDCT  DXVA2_ModeVC1_IDCT  DXVA2_ModeH264_VLD_NoFGT  
   Deinterlace Caps: {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YUY2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(UYVY,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(YV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(NV12,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC1,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC2,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC3,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
                     {BF752EF6-8CC4-457A-BE1B-08BD1CAEEE9F}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,1) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_EdgeFiltering 
                     {335AA36E-7884-43A4-9C91-7F87FAF3E37E}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend DeinterlaceTech_BOBVerticalStretch 
                     {5A54A0C9-C7EC-4BD9-8EDE-F3C75DC4393B}: Format(In/Out)=(IMC4,YUY2) Frames(Prev/Fwd/Back)=(0,0,0) Caps=VideoProcess_YUV2RGB VideoProcess_StretchX VideoProcess_StretchY VideoProcess_AlphaBlend 
       D3D9 Overlay: Supported
            DXVA-HD: Supported
       DDraw Status: Enabled
         D3D Status: Enabled
         AGP Status: Enabled

**Comment by JoshEngebretson** [comment]
Does this happen in the Unity editor or solely in deployment?  Are you able to run the demo executable? http://www.uwebkit.com/static/downloads/uwebkit/uWebKit2_Demo_Windows.zip

**Comment by st0nerhat** [comment]
The DirectX 11 version crashes, but the DirectX 9 version works.

**Comment by st0nerhat** [comment]
DX 9 is an acceptable workaround.
