### ISSUE TITLE
MipMap uWebKit 

### ISSUE THREAD

**Issue by Jamesmallon1** [uWebKit/uWebKit#146]
Hello there,

in UWKWebView.cs I have enabled mipmapping bool option as:

WebTexture = new Texture2D( MaxWidth, MaxHeight, format, true);

However whenever i start the application the texture is a gray/black gradient?!
All Help appreciated Thank You!
James

**Comment by JoshEngebretson** [comment]
Hello mipmapping is not supported as the Texture2D is a render target internally

**Comment by Jamesmallon1** [comment]
Will it ever be supported?

**Comment by JoshEngebretson** [comment]
In order to provide fast rendering, the internal texture is a shared GPU resource which don't have mipmaps, as the texture is also constantly changing, mipmaps would be constantly regenerated leading to further performance degradation.
