### ISSUE TITLE
WebView does not appear on Mac OS 10.10.4 if not running in highest/native resolution

### ISSUE THREAD

**Issue by st0nerhat** [uWebKit/uWebKit#149]
OS: Mac OS 10.10.4
Unity version: 5.0.0f4, 5.0.2f1
Architecture: x86
Mac Full Screen Mode: "Fullscreen Window"

If I use any resolution other then the native resolution, the webview does not appear. This seems independent of how I size the webview.

Any resolution works fine if I run the game in windowed mode.

When "Mac Fullscreen Mode" is set to "Capture Display" the WebView does appear. However, Capture Display is a deprecated mode and does undesirable things to the display of my game.

The problem is reproducible using the UWebKit Demo app for mac.

1. Launch the UWebKit Demo app
2. Uncheck "Windowed"
3. Choose a resolution lower than the highest setting
4. Launch the app
5. Observe a black screen

**Comment by st0nerhat** [comment]
Player log:

Initialize engine version: 5.0.0f4 (5b98b70ebeb9)
GfxDevice: creating device client; threaded=1
OpenGL:
    Version:  OpenGL 2.1 [2.1 INTEL-10.0.31]
    Renderer: Intel HD Graphics 3000 OpenGL Engine
    Vendor:   Intel Inc.
    VRAM:     579 MB
    Extensions: GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod 
GL: Detected 579 MB VRAM
Begin MonoManager ReloadAssembly
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/UnityEngine.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/UnityEngine.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/Assembly-CSharp-firstpass.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/Assembly-CSharp.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/Assembly-CSharp.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/Assembly-UnityScript-firstpass.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/Assembly-UnityScript-firstpass.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/Assembly-UnityScript.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/Assembly-UnityScript.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/UnityEngine.UI.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/UnityEngine.UI.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/ArabicSupport.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/ArabicSupport.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/ES2PlayMaker.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/ES2PlayMaker.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/ES2.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/ES2.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/LitJson.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/LitJson.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/MoodkieSecurity.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/MoodkieSecurity.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/P31RestKit.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/P31RestKit.dll into Unity Child Domain
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/PlayMaker.dll (this message is harmless)
Loading /Volumes/*****************/Contents/Resources/Data/Managed/PlayMaker.dll into Unity Child Domain
- Completed reload, in  0.102 seconds
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/System.Core.dll (this message is harmless)
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/System.dll (this message is harmless)
Platform assembly: /Volumes/*****************/Contents/Resources/Data/Managed/System.Xml.dll (this message is harmless)
Start
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

Setting up 2 worker threads for Enlighten.
  Thread -> id: b0df5000 -> priority: 1 
  Thread -> id: b0e77000 -> priority: 1 
InitAuthStrategy
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

Connect
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

QObject::killTimer(): Error: timer id 1967277635 is not valid for object 0x3527390 (), timer has not been killed
Javascript: document.body doesn't exist. Modernizr hyphens test needs it. 4 http://staging.filamentgames.com/sites/all/libraries/modernizr/modernizr.js?nrlo77
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

Javascript: WebSocket network error: Host not found 0 http://staging.filamentgames.com/user/login?destination=oauth2/authorize
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebug.gen.cpp Line: 56)

2015-07-30 17:53:07.503 UWKProcess[13701:1044606] Cannot find executable for CFBundle 0xd64e0d0 </Library/Internet Plug-Ins/Unused> (not loaded)
2015-07-30 17:53:09.629 UWKProcess[13701:1044606] Error loading /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/MacOS/JavaAppletPlugin:  dlopen(/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/MacOS/JavaAppletPlugin, 265): no suitable image found.  Did find:
	/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/MacOS/JavaAppletPlugin: mach-o, but wrong architecture
QObject::killTimer(): Error: timer id 1 is not valid for object 0xbffffb90 (), timer has not been killed

**Comment by st0nerhat** [comment]
Never mind.

**Comment by st0nerhat** [comment]
Ok, this is still in issue I just found that there are ways to get it to working in other Fullscreen Modes, but not in all cases.

**Comment by st0nerhat** [comment]
I implemented a workaround. For anyone that is interested, here is a snippet.

```
	#if UNITY_STANDALONE_OSX
			//Force native resolution on OSX
			while (Screen.fullScreen && (Screen.width != Screen.currentResolution.width || Screen.height != Screen.currentResolution.height)) {
				Screen.SetResolution(Screen.currentResolution.width, Screen.currentResolution.height, true);
				yield return new WaitForFixedUpdate();
			}
	#endif
```

**Comment by JoshEngebretson** [comment]
Hello, thanks for the snippet.  

This is really strange as uWebKit ultimately is just a Texture2D, though it is rendered to texture: 

https://github.com/uWebKit/uWebKit/blob/master/uWebKitNative/UWKCommon/uwk_renderer_gl.cpp
