### ISSUE TITLE
Touches control for web view ?

### ISSUE THREAD

**Issue by StrukovS** [uWebKit/uWebKit#154]
We have currently using WebView on system under Windows 8 with multytouch support.

Wen comparing same web page in Internet Explorer and our application with uWKWebView - we can see that touches controling WebView via mouse click emulation (for exaple, page can be scrolled only in scrollbar area). This is not best experence for users.
In Internet Explorer we can scroll page simple with touches within inactive (non clickable) area of web page.
Is this functionality avaliable for uWEBKit (may be i missed something) or can be added ?

If i should implement this functionality by myself - i can see following problems:
I can see:
    [DllImport ("UWKPlugin")]
    public static extern void UWK_MsgSetScrollPosition(uint browserID, int x, int y);
But i can't get current scroll position (if it changed via scroll bars) & scroll range.

Also i don't know functionality for hit testing (check is item clickable (interactible) under given pixel position) on web page.

Any help?

**Comment by StrukovS** [comment]
So any suggestion, or any help?

**Comment by JoshEngebretson** [comment]
The WebView does not have touch enabled controls.  You would need to map touch controls to the mouse controls provided.

**Comment by StrukovS** [comment]
We are wrapping mouse events from unity to WebView. As i write before, touches works because of system or/and unity emulate mouse events from touches. And because of this basic touches control works.
But if we look at "Internet Explorer" for example, we can scroll page - with touch within page in any non interacteble place and just drug in sides.
If input works in mouse emulation mode we can scroll only with touching at scroll bar areas.

So i'm asking in other words...
Is possible to improve uWebkit functionality - add in WebView hittesting (ask is any active web element, that can accept events like button) and scrolling (get/set scroll position and get scroll range) ?

At present implementation - i only can see ability to set scroll position.
Waiting your respond.
Thanks.

**Comment by AntonMedvedev** [comment]
Hi, 
We look forward to your reply.
Can you do the following:
1. UWK_MsgGetScrollPosition(uint browserID, out int x, out int y);
2. UWK_MsgGetMaxScrollPosition(uint browserID, out int xMax, out int yMax);
You do not plan to make native support for touch screens?
The question is very important to us, we use our app on the touch screen, and we really need the ability to scroll through touch.
Thanks.

**Comment by JoshEngebretson** [comment]
Hello,  uWebKit2 does not support touch input at this time.

**Comment by AntonMedvedev** [comment]
To fully control the scroll you could make these 2 methods?
1. UWK_MsgGetScrollPosition(uint browserID, out int x, out int y);
2. UWK_MsgGetMaxScrollPosition(uint browserID, out int xMax, out int yMax);
