### ISSUE TITLE
GamePad support

### ISSUE THREAD

**Issue by simoky** [uWebKit/uWebKit#160]
Hi I have just purchased uWebKit and I must say I am very impressed, I am currently working on a virtual reality application within Unity and I have a slight problem. I have got it working when I focus on a button or link by looking at it and then selecting using the game pad x button. The issue is when I press forwards on the controller to walk it seems to jump sometimes and I miss a few frames. I would be grateful if anybody could point me in the right direction.

**Comment by JoshEngebretson** [comment]
Hello,  I am glad uWebKit is working well for you. I am unsure what this issue is regarding, what is jumping?

**Comment by simoky** [comment]
When I press on the gamepad to walk forwards, I go forward and then suddenly I move a lot further than I should, like judder or something affecting the frame rate. When i turn the UWebKit webtexture off its fine.

**Comment by simoky** [comment]
Thanks, it was sorted when I disabled the mouse in Unity. Thanks for all the support
