### ISSUE TITLE
loading  new url through UWKWebView.AddToGameObject.

### ISSUE THREAD

**Issue by simoky** [uWebKit/uWebKit#163]
![capture88](https://cloud.githubusercontent.com/assets/10655449/11179464/50e83fdc-8c4b-11e5-9461-3e9d4f66e22a.JPG)
Sorry I,ve being trying for days now to get this working. I have a button in Unity, that when pressed it changes the the monitors webpage. it looks as if it working as it passes the url, but the moniter screen just goes blank. there are no errors. I would be grateful if anybody could point me in the right direction

**Comment by simoky** [comment]
Sorry I,ve being trying for days now to get this working. I have a button in Unity, that when pressed it changes the the monitors webpage. it looks as if it working as it passes the url, but the moniter screen just goes blank. there are no errors. I would be grateful if anybody could point me in the right direction
![capture88](https://cloud.githubusercontent.com/assets/10655449/11187583/e7f6e9c2-8c7e-11e5-9dd7-bf53a16da9cf.JPG)

**Comment by simoky** [comment]
Warning: Unable to get view for message: UMSG_VIEW_LOADFINISHED
UnityEngine.Debug:Log(Object)
UWKCore:ProcessMessage(UWKMessage&) (at Assets/uWebKit/Internal/UWKCore.cs:141)
UWKPlugin:processMessage(IntPtr) (at Assets/uWebKit/Internal/UWKPlugin.cs:385)
UWKPlugin:UWK_Update()
UWKCore:Update() (at Assets/uWebKit/Internal/UWKCore.cs:98)

**Comment by simoky** [comment]
Warning: Unable to get view for message: UMSG_VIEW_LOADPROGRESS
UnityEngine.Debug:Log(Object)
UWKCore:ProcessMessage(UWKMessage&) (at Assets/uWebKit/Internal/UWKCore.cs:141)
UWKPlugin:processMessage(IntPtr) (at Assets/uWebKit/Internal/UWKPlugin.cs:385)
UWKPlugin:UWK_Update()
UWKCore:Update() (at Assets/uWebKit/Internal/UWKCore.cs:98)

**Comment by JoshEngebretson** [comment]
Hello,

Why destroy and then recreate the WebView component, instead of just loading the new page?

- Josh

**Comment by simoky** [comment]
Because I tried that and the previous website was still there.

**Comment by simoky** [comment]
I've just noticed if I dont destroy the previous webpage i get two UWK webviews.
![tt](https://cloud.githubusercontent.com/assets/10655449/11225460/212f8e30-8d72-11e5-98e4-1e4407f44536.JPG)

**Comment by simoky** [comment]
Hi Josh,

I just tested that LoadURL method on my own and then in a new scene and the same result. No change, the url is getting passed but it not loading. Could this be because of the Unity version its 5.2.2f1 of because I using windows 10?

**Comment by JoshEngebretson** [comment]
Try creating a new project, bringing the uWebKit package in, and opening the example browser scene.  The bookmark buttons all use LoadURL: 

https://github.com/uWebKit/uWebKit/blob/master/uWebKit/Assets/uWebKitExamples/Scripts/WebBrowser.cs#L299

**Comment by simoky** [comment]
It works I will have a look at my code again thanks for the quick reply

**Comment by simoky** [comment]
Thanks for the swift reply I was under pressure on my FinalYearProject and did not realise the mistake in my code, as I was trying everything.

The solution was simple. 
![solution](https://cloud.githubusercontent.com/assets/10655449/11252445/2b7981c2-8e2e-11e5-94f3-3c8eea7b0c3a.JPG)

Thanks for the help
