### ISSUE TITLE
MacOSX - Package seems to not be working with unity 5.3?

### ISSUE THREAD

**Issue by FoolishFrost** [uWebKit/uWebKit#166]
Package seems to not be working with unity 5.3?

I am getting a grey browser windows with no data every time I try to run it in either an application or in editor on a mac.

Any confirmation of this working in unity 5.3?

**Comment by JoshEngebretson** [comment]
It is working on Windows 5.3, I am also seeing an issue on OSX and am looking into it.

**Comment by JoshEngebretson** [comment]
Hello, uWebKit2 currently requires OpenGL2 profile:

<img width="370" alt="screen shot 2015-12-17 at 1 25 18 pm" src="https://cloud.githubusercontent.com/assets/376203/11882529/c037d904-a4c1-11e5-91c8-d110a7479e95.png">

We'll look into making it work with OpenGLCore and Metal (which is still experimental on Unity 5.3)

**Comment by JoshEngebretson** [comment]
Here is an updated package with Unity 5.3 OpenGLCore support:

http://www.uwebkit.com/static/downloads/uwebkit/uWebKit2_20p9.unitypackage

- Josh
