### ISSUE TITLE
A question about 'Develop webplayer that use uWebkit'

### ISSUE THREAD

**Issue by D4VID-K** [uWebKit/uWebKit#168]
Hello, I am a software devleloper from korea.

I'm writing this mail for some questions about the 'uWebkit'.

Currently, I've been using 'UnityEngine 5.2.1f' and 'web-player platform'.

I'm trying to develop a webview with the 'uWebkit', but I have some problems.

#1. After running the 'uWebkit' and converting to 'web-player' to build, an error occurs at... 'System.MethodAccessException: Attempt ... <filename unknown>:0'

- I wonder if it's right to use (Preprocessing) to correct this error.

#2. After correcting the problem #1, I built it and ran it.(Build-Play) Then again the same error occurs at... 'System.MethodAccessException: Attempt ... <filename unknown>:0'

I could not solve this problem, and I would really appreciate it if you could help me with this problem.

Thank your for reading my poor explanation.

![issue_1_code](https://cloud.githubusercontent.com/assets/16331492/11912742/4e985c8c-a68e-11e5-8aa7-da5fde276304.png)

![issue_1_log](https://cloud.githubusercontent.com/assets/16331492/11912744/579ba640-a68e-11e5-8da0-e3b153f01e25.png)

![issue_2_code](https://cloud.githubusercontent.com/assets/16331492/11912745/5944ebb4-a68e-11e5-8011-2cbcece64a8c.png)

![issue_2_log](https://cloud.githubusercontent.com/assets/16331492/11912747/5c4170e4-a68e-11e5-878f-9b1efaebcc8e.png)

**Comment by JoshEngebretson** [comment]
uWebKit is for Unity PC and Mac standalone builds, it does not support the web player platform
