### ISSUE TITLE
Github Repository not up to date with the Unity package on the Website

### ISSUE THREAD

**Issue by fngryboi** [uWebKit/uWebKit#19]
Would be nice if the repository here would contain the same contents as the download, as I want the convenience of being able to fork this one to clone it inside my Unity Project to be able to just fetch the newest version into the project in a easy way. Right now I've seen two updates on the website (p2 and p3), but no updates here...

**Comment by JoshEngebretson** [comment]
The plan is to keep them in sync, I'll get an update pushed here today

**Comment by fngryboi** [comment]
Nice! A lot easier to just grab the latest version now :)
