### ISSUE TITLE
window.uwkQuery is not a function

### ISSUE THREAD

**Issue by 2emoore4** [uWebKit/uWebKit#23]
hey, I've got a UWKWebView (from the v3 beta) in my scene. I'm trying to send messages to Unity from a javascript web app that is loaded into the web view from a local file. I'm using the exact (copy-pasted) [code from the getting started guide](https://github.com/uWebKit/uWebKit/wiki/Getting-Started-with-the-uWebKit3-Beta#calling-unity-from-javascript-with-webqueries).

when my javascript calls window.uwkQuery(...), I get a js error in the Unity console: INFO: WebViewJS: Uncaught TypeError: window.uwkQuery is not a function

looks like the function uwkQuery is never getting added to the js window object. I even tried repeatedly checking for uwkQuery, once per second, in case there was some timing issue:

`setInterval(function() {
      console.log("uwkQuery !== undefined? : " + (window.uwkQuery !== undefined));
}, 1000);`

still, window.uwkQuery remains undefined

ever see any similar issues?

thanks.

**Comment by JoshEngebretson** [comment]
Hello, "atomicQuery" was renamed to "uwkQuery", if atomicQuery exists this would be an older build.

**Comment by 2emoore4** [comment]
yep, that's it. thanks for the quick reply!!
