### ISSUE TITLE
UWKPlugin.UWK_PostUnityKeyEvent not functioning the same

### ISSUE THREAD

**Issue by emJD** [uWebKit/uWebKit#27]
Hi,

The company I work for just purchased uWebKit3.  I have had the personal edition of the uWebKit3 working by using this method:

 UWKPlugin.UWK_PostUnityKeyEvent(ID, ref event);

I am passing the same data as I was before but only the backspace keyboard event will process (characters will not process). We need this method to work because we use our own virtual keyboard within Unity and create the keyboard event and process it through that method.

Thank You

**Comment by JoshEngebretson** [comment]
We have introduced an injection method for an upcoming release
