### ISSUE TITLE
Request mobile site

### ISSUE THREAD

**Issue by Naphier** [uWebKit/uWebKit#29]
Many sites like youtube have a mobile version. Unfortunately if your User agent is recognized as a desktop browser these sites will ignore the m prefix and serve the desktop version. Oftentimes in a limited space environment it's quiet helpful to have a large UI.

I'd like to request that we are able to customize the user agent for the browser. 

Thanks!

**Comment by JoshEngebretson** [comment]
Hello, it is possible to configure both the user agent as well as just the product section of it:

https://github.com/uWebKit/uWebKit/blob/master/uWebKit/Assets/uWebKit/UWKConfig.cs#L25

Please let me know if this isn't working for your use case and I will reopen the issue.

**Comment by Naphier** [comment]
It does request the mobile site correctly, but I've not been able to get it to play youtube video when the UA is set. Youtube either says my browser doesn't support HTML5 video. Or it displays a black screen video player that won't play.

    UserAgent = "Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus Build/JRN84D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19";
    UserAgentProductVersion = "Chrome/18.0.1025.166";

Maybe I'm doing something wrong? 
Thanks!
