### ISSUE TITLE
Issues running on Windows  7 64 bit for uWebKit3 Beta Package

### ISSUE THREAD

**Issue by TheNef** [uWebKit/uWebKit#5]
Hello there,
trying to test out the examples and I'm getting the following

DllNotFoundException: Assets/uWebKit/Internal/Plugins/x86_64/UWKPlugin.dll
UWKPlugin.Initialize () (at Assets/uWebKit/Internal/UWKPlugin.cs:57)
UWKCore.Init () (at Assets/uWebKit/Internal/UWKCore.cs:40)
UWKWebView.Awake () (at Assets/uWebKit/UWKWebView.cs:183)

The examples for version 2 worked without issue

**Comment by JoshEngebretson** [comment]
Thanks for the report, checking into the dependencies on UWKPlugin.dll

Are you running a 32 bit Unity editor by chance?

**Comment by TheNef** [comment]
Hello again,

I'm running 64 bit version.

Cheers

**Comment by JoshEngebretson** [comment]
Please try this updated package: 

http://www.uwebkit.com/static/downloads/uwebkit/uWebKit3_Beta1_p1.zip

It addresses a dll dependency that may not have been loading.

**Comment by TheNef** [comment]
Hello there,
thanks for the quick reply works a treat now.

Cheers Kevin
